package com.google.android.gms.d;

public enum b
{
  private final String zzhI;
  
  static
  {
    zzdA = new b("BLACKLISTED_BEHAVIOR", 19, "blacklisted_behavior");
    zzdB = new b("CACHE_BUSTER", 20, "cache_buster");
    zzdC = new b("CACHE_BUSTER_VALUE", 21, "cache_buster_value");
    zzdD = new b("CAMPAIGN_CONTENT_KEY", 22, "campaign_content_key");
    zzdE = new b("CAMPAIGN_CONTENT_OVERRIDE", 23, "campaign_content_override");
    zzdF = new b("CAMPAIGN_COOKIE_TIMEOUT", 24, "campaign_cookie_timeout");
    zzdG = new b("CAMPAIGN_MEDIUM_KEY", 25, "campaign_medium_key");
    zzdH = new b("CAMPAIGN_MEDIUM_OVERRIDE", 26, "campaign_medium_override");
    zzdI = new b("CAMPAIGN_NAME_KEY", 27, "campaign_name_key");
    zzdJ = new b("CAMPAIGN_NAME_OVERRIDE", 28, "campaign_name_override");
    zzdK = new b("CAMPAIGN_NO_KEY", 29, "campaign_no_key");
    zzdL = new b("CAMPAIGN_SOURCE_KEY", 30, "campaign_source_key");
    zzdM = new b("CAMPAIGN_SOURCE_OVERRIDE", 31, "campaign_source_override");
    zzdN = new b("CAMPAIGN_TERM_KEY", 32, "campaign_term_key");
    zzdO = new b("CAMPAIGN_TERM_OVERRIDE", 33, "campaign_term_override");
    zzdP = new b("CAMPAIGN_TRACK", 34, "campaign_track");
    zzdQ = new b("CATEGORY", 35, "category");
    zzdR = new b("CHECK_VALIDATION", 36, "check_validation");
    zzdS = new b("CHILD_INDEX", 37, "child_index");
    zzdT = new b("CLEAR_PERSISTENT_DATA_LAYER_PREFIX", 38, "clear_data_layer_prefix");
    zzdU = new b("CLICK_ID", 39, "click_id");
    zzdV = new b("CLIENT_INFO", 40, "client_info");
    zzdW = new b("COLLECT_ADID", 41, "collect_adid");
    zzdX = new b("COMPANY", 42, "company");
    zzdY = new b("COMPONENT", 43, "component");
    zzdZ = new b("CONTENT_DESCRIPTION", 44, "content_description");
    zzea = new b("CONTENT_GROUP", 45, "content_group");
    zzeb = new b("CONVERSION_ID", 46, "conversion_id");
    zzec = new b("COOKIE_DOMAIN", 47, "cookie_domain");
    zzed = new b("COOKIE_EXPIRATION", 48, "cookie_expiration");
    zzee = new b("COOKIE_NAME", 49, "cookie_name");
    zzef = new b("COOKIE_PATH", 50, "cookie_path");
    zzeg = new b("COOKIE_PATH_COPY", 51, "cookie_path_copy");
    zzeh = new b("COUNTRY", 52, "country");
    zzei = new b("CSS_ID", 53, "css_id");
    zzej = new b("CSS_IMPORTANT", 54, "css_important");
    zzek = new b("CSS_PROPERTY", 55, "css_property");
    zzel = new b("CSS_RULE", 56, "css_rule");
    zzem = new b("CSS_VALUE", 57, "css_value");
    zzen = new b("CURRENCY_CODE", 58, "currency_code");
    zzeo = new b("CUSTOM_URL_SOURCE", 59, "custom_url_source");
    zzep = new b("CUSTOM_VARS", 60, "custom_vars");
    zzeq = new b("CUSTOMER_ID", 61, "customer_id");
    zzer = new b("DATA_LAYER_VERSION", 62, "data_layer_version");
    zzes = new b("DATA_PROVIDER_ID", 63, "data_provider_id");
    zzet = new b("DEBUG", 64, "debug");
    zzeu = new b("DECODE", 65, "decode");
    zzev = new b("DECORATE_FORM", 66, "decorate_form");
    zzew = new b("DECORATE_FORMS_AUTO_LINK", 67, "decorate_forms_auto_link");
    zzex = new b("DECORATE_LINK", 68, "decorate_link");
    zzey = new b("DEFAULT_PAGES", 69, "default_pages");
    zzez = new b("DEFAULT_VALUE", 70, "default_value");
    zzeA = new b("DEPENDENCIES", 71, "dependencies");
    zzeB = new b("DETECT_FLASH", 72, "detect_flash");
    zzeC = new b("DETECT_TITLE", 73, "detect_title");
    zzeD = new b("DIMENSION", 74, "dimension");
    zzeE = new b("DOMAIN_NAME", 75, "domain_name");
    zzeF = new b("DOUBLE_CLICK", 76, "double_click");
    zzeG = new b("ECOMMERCE_MACRO_DATA", 77, "ecommerce_macro_data");
    zzeH = new b("ECOMMERCE_USE_DATA_LAYER", 78, "ecommerce_use_data_layer");
    zzeI = new b("ELEMENT", 79, "element");
    zzeJ = new b("ELEMENT_ID", 80, "element_id");
    zzeK = new b("ELEMENTS", 81, "elements");
    zzeL = new b("EMAIL", 82, "email");
    zzeM = new b("EMPLOYEE_RANGE", 83, "employee_range");
    zzeN = new b("ENABLE_ECOMMERCE", 84, "enable_ecommerce");
    zzeO = new b("ENABLE_ALL_VIDEOS", 85, "enable_all_videos");
    zzeP = new b("ENABLE_PRODUCT_REPORTING", 86, "enable_product_reporting");
    zzeQ = new b("ENABLE_REMARKETING_LISTS", 87, "enable_remarketing_lists");
    zzeR = new b("ESCAPE", 88, "escape");
    zzeS = new b("EVENT_ACTION", 89, "event_action");
    zzeT = new b("EVENT_CATEGORY", 90, "event_category");
    zzeU = new b("EVENT_LABEL", 91, "event_label");
    zzeV = new b("EVENT_VALUE", 92, "event_value");
    zzeW = new b("EXCEPTION_DESCRIPTION", 93, "exception_description");
    zzeX = new b("EXCEPTION_FATAL", 94, "exception_fatal");
    zzeY = new b("EXPERIMENT_COMBINATION", 95, "experiment_combination");
    zzeZ = new b("EXPERIMENT_ID", 96, "experiment_id");
    zzfa = new b("EXPERIMENT_KEY", 97, "experiment_key");
    zzfb = new b("FAILED_BEHAVIOR", 98, "failed_behavior");
    zzfc = new b("SECTION_INDEX", 99, "section_index");
    zzfd = new b("FIELDS_TO_SET", 100, "fields_to_set");
    zzfe = new b("FORCE_SSL", 101, "force_ssl");
    zzff = new b("FORM_OBJECT", 102, "form_object");
    zzfg = new b("FUNCTION", 103, "function");
    zzfh = new b("FUNCTION_CALL_NAME", 104, "function_call_macro_name");
    zzfi = new b("GROUP", 105, "group");
    zzfj = new b("HIT_CALLBACK", 106, "hit_callback");
    zzfk = new b("HTML", 107, "html");
    zzfl = new b("ID", 108, "id");
    zzfm = new b("IGNORED_ORGANIC", 109, "ignored_organic");
    zzfn = new b("IGNORED_REF", 110, "ignored_ref");
    zzfo = new b("IGNORE_CASE", 111, "ignore_case");
    zzfp = new b("INPUT", 112, "input");
    zzfq = new b("INPUT_FORMAT", 113, "input_format");
    zzfr = new b("INSTANCE_NAME", 114, "instance_name");
    zzfs = new b("INSTANCE_LABEL", 115, "instance_label");
    zzft = new b("INTERVAL", 116, "interval");
    zzfu = new b("ITEM_SEPARATOR", 117, "item_separator");
    zzfv = new b("JAVASCRIPT", 118, "javascript");
    zzfw = new b("JSON", 119, "json");
    zzfx = new b("KEYWORD", 120, "keyword");
    zzfy = new b("KEY_VALUE_SEPARATOR", 121, "key_value_separator");
    zzfz = new b("LABEL", 122, "label");
    zzfA = new b("LANGUAGE", 123, "language");
    zzfB = new b("LIMIT", 124, "limit");
    zzfC = new b("LINK", 125, "link");
    zzfD = new b("LINK_BY_POST", 126, "link_by_post");
    zzfE = new b("LINK_ID", 127, "link_id");
    zzfF = new b("LIVE_ONLY", 128, "live_only");
    zzfG = new b("LOCAL_GIF_PATH", 129, "local_gif_path");
    zzfH = new b("LOCALE", 130, "locale");
    zzfI = new b("LOCATION", 131, "location");
    zzfJ = new b("MAP", 132, "map");
    zzfK = new b("MAX", 133, "max");
    zzfL = new b("METRIC", 134, "metric");
    zzfM = new b("MIN", 135, "min");
    zzfN = new b("MODE", 136, "mode");
    zzfO = new b("NAME", 137, "name");
    zzfP = new b("NAMESPACE_CODE", 138, "namespace_code");
    zzfQ = new b("NAMESPACE_ID", 139, "namespace_id");
    zzfR = new b("NAMESPACE_VALUE", 140, "namespace_value");
    zzfS = new b("NONINTERACTION", 141, "noninteraction");
    zzfT = new b("NOT_DEFAULT_MACRO", 142, "not_default_macro");
    zzfU = new b("NO_PADDING", 143, "no_padding");
    zzfV = new b("NUMBER", 144, "number");
    zzfW = new b("OPTOUT", 145, "optout");
    zzfX = new b("ORDER", 146, "order");
    zzfY = new b("ORDER_ID", 147, "order_id");
    zzfZ = new b("ORDER_VALUE", 148, "order_value");
    zzga = new b("ORDINAL", 149, "ordinal");
    zzgb = new b("ORGANIC", 150, "organic");
    zzgc = new b("OUTPUT_FORMAT", 151, "output_format");
    zzgd = new b("PAGE", 152, "page");
    zzge = new b("PAGE_PATH", 153, "page_path");
    zzgf = new b("PARTITION", 154, "partition");
    zzgg = new b("PERCENTAGE", 155, "percentage");
    zzgh = new b("PIXEL", 156, "pixel");
    zzgi = new b("PLACEMENT", 157, "placement");
    zzgj = new b("PLATFORM", 158, "platform");
    zzgk = new b("POSITION", 159, "position");
    zzgl = new b("PRICES", 160, "prices");
    zzgm = new b("PRIORITY", 161, "priority");
    zzgn = new b("PRODUCT", 162, "product");
    zzgo = new b("PRODUCT_DATA", 163, "product_data");
    zzgp = new b("PRODUCT_ID", 164, "product_id");
    zzgq = new b("PRODUCT_IDS", 165, "product_ids");
    zzgr = new b("PRODUCT_SETTING_FIELD_PATH", 166, "product_setting_field_path");
    zzgs = new b("PUSH_AFTER_EVALUATE", 167, "push_after_evaluate");
    zzgt = new b("QUANTITY", 168, "quantity");
    zzgu = new b("QUERY_KEY", 169, "query_key");
    zzgv = new b("QUERY_LISTS", 170, "query_lists");
    zzgw = new b("REFERRER", 171, "referrer");
    zzgx = new b("REFERRER_OVERRIDE", 172, "referrer_override");
    zzgy = new b("REQUIRES_CONTENT", 173, "requires_content");
    zzgz = new b("REVENUE", 174, "revenue");
    zzgA = new b("SAMPLE_RATE", 175, "sample_rate");
    zzgB = new b("SELECTOR", 176, "selector");
    zzgC = new b("SEND_HITS_TO_GOOGLE", 177, "send_hits_to_google");
    zzgD = new b("SESSION_CONTROL", 178, "session_control");
    zzgE = new b("SESSION_COOKIE_TIMEOUT", 179, "session_cookie_timeout");
    zzgF = new b("SITE_SPEED_SAMPLE_RATE", 180, "site_speed_sample_rate");
    zzgG = new b("SOCIAL_ACTION", 181, "social_action");
    zzgH = new b("SOCIAL_ACTION_TARGET", 182, "social_action_target");
    zzgI = new b("SOCIAL_NETWORK", 183, "social_network");
    zzgJ = new b("SOCIAL_USE_DATA_LAYER", 184, "social_use_data_layer");
    zzgK = new b("SERVER_SIDE", 185, "server_side");
    zzgL = new b("STANDARD_INDUSTRIAL_CLASSIFICATION", 186, "standard_industrial_classification");
    zzgM = new b("STRING", 187, "string");
    zzgN = new b("STRIP_WWW", 188, "strip_www");
    zzgO = new b("TAG_ID", 189, "tag_id");
    zzgP = new b("TAG_LIST", 190, "tag_list");
    zzgQ = new b("TAG_LIST_CONTEXT", 191, "tag_list_context");
    zzgR = new b("TAG_LIST_INDEX", 192, "tag_list_index");
    zzgS = new b("TAG_REFERENCE", 193, "tag_reference");
    zzgT = new b("TARGET_CSS_ID", 194, "target_css_id");
    zzgU = new b("TARGET_ELEMENTS", 195, "target_elements");
    zzgV = new b("TARGET_SELECTOR", 196, "target_selector");
    zzgW = new b("TARGET_URL", 197, "target_url");
    zzgX = new b("TEXT", 198, "text");
    zzgY = new b("TIMING_CATEGORY", 199, "timing_category");
    zzgZ = new b("TIMING_LABEL", 200, "timing_label");
    zzha = new b("TIMING_SAMPLE_RATE", 201, "timing_sample_rate");
    zzhb = new b("TIMING_VALUE", 202, "timing_value");
    zzhc = new b("TIMING_VAR", 203, "timing_var");
    zzhd = new b("TITLE", 204, "title");
    zzhe = new b("TRACK_APPVIEW", 205, "track_appview");
    zzhf = new b("TRACK_DATA", 206, "track_data");
    zzhg = new b("TRACK_EVENT", 207, "track_event");
    zzhh = new b("TRACK_EXCEPTION", 208, "track_exception");
    zzhi = new b("TRACK_SOCIAL", 209, "track_social");
    zzhj = new b("TRACK_TIMING", 210, "track_timing");
    zzhk = new b("TRACK_TRANSACTION", 211, "track_transaction");
    zzhl = new b("TRACKER_NAME", 212, "tracker_name");
    zzhm = new b("TRACKING_ID", 213, "tracking_id");
    zzhn = new b("TRANSACTION_DATALAYER_MAP", 214, "transaction_datalayer_map");
    zzho = new b("TRANSACTION_ID", 215, "transaction_id");
    zzhp = new b("TRANSACTION_ITEM_DATALAYER_MAP", 216, "transaction_item_datalayer_map");
    zzhq = new b("TRANSACTION_VARIABLE", 217, "transaction_variable");
    zzhr = new b("TYPE", 218, "type");
    zzhs = new b("UNIQUE_TRIGGER_ID", 219, "unique_trigger_id");
    zzht = new b("UNREPEATABLE", 220, "unrepeatable");
    zzhu = new b("URL", 221, "url");
    zzhv = new b("USE_DATA_LAYER", 222, "use_data_layer");
    zzhw = new b("USE_HASH", 223, "use_hash");
    zzhx = new b("USE_IFRAME", 224, "use_iframe");
    zzhy = new b("USE_IMAGE_TAG", 225, "use_image_tag");
    zzhz = new b("USE_POSTSCRIBE", 226, "use_postscribe");
  }
  
  private b(String paramString)
  {
    zzhI = paramString;
  }
  
  public String toString()
  {
    return zzhI;
  }
}

/* Location:
 * Qualified Name:     com.google.android.gms.d.b
 * Java Class Version: 6 (50.0)
 * JD-Core Version:    0.7.1
 */